import Menu from '@/components/menu/menu'
import '../styles/globals.scss'
import { Poppins } from '@next/font/google';
import Image from 'next/image'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Menu menuItems={
          [
            {
              name: 'Home',
              link: '/'
            },
            {
              name: 'Blog',
              link: '/blog'
            },
            {
              name: 'Projects',
              link: '/projects'
            },
          ]

        } />
        {children}
        <footer>
          {/*
          <a href="https://buttercms.com" target="_blank" rel="noopener noreferrer">
            <Image src="/butter-w.png" alt="ButterCMS logo" width={150} height={100} />
          </a>
          */}
          <div className="copiright">
            Created by <a href="/">Jose Dacosta</a>
          </div>
        </footer>
      </body>
    </html>
  )
}
