import type { Metadata } from "next";
import { Quantico } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";

const quantico = Quantico({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quantico.variable} antialiased container mx-auto px-4`}
      >
        <div className="min-h-screen font-[family-name:var(--font-quantico)] flex flex-col gap-8">
          <Menu
            menuItems={[
              {
                name: "Home",
                link: "/",
              },
              {
                name: "Blog",
                link: "/blog",
              },
            ]}
          />
          <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start flex-1">
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center p-4 w-full bg-yaleblue text-white">
            Made with ❤️ by José
          </footer>
        </div>
      </body>
    </html>
  );
}
