import Menu from '@/components/menu/menu'
import '../../styles/globals.scss'
import { Poppins } from "next/font/google";
import Image from 'next/image'
import  { ThemeProvider } from '@/components/ThemeContext/ThemeContext';
import BodyContainer from '@/components/BodyContainer/BodyContainer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <ThemeProvider>
      <BodyContainer>{children}</BodyContainer>
      </ThemeProvider>
    </html>
  )
}
